version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - approve:
          type: approval
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - run: node --version